// Model/AppointmentPreBookingModel.cs
using Dapper.Contrib.Extensions;

namespace Medico_Backend.Model
{
    [Table("appointment_pre_booking")]
    public class AppointmentPreBookingModel
    {
        [Key] // auto-generated by DB now
        public long preferenceid { get; set; }

        public string? tenant_code { get; set; }

        public string? custcode { get; set; }

        public int? dcode { get; set; }

        public string? husband_name { get; set; }

        public string? service_type { get; set; }

        public string? test_name { get; set; }

        public DateTime? appointment_date { get; set; }

        public string? remarks { get; set; }
        public string status { get; set; } = "booked";

        public bool deleted { get; set; } = false;

        public int usercode { get; set; } = 1;

        public int computercode { get; set; } = 1;

        public DateTime entereddate { get; set; }

        public DateTime ibsdate { get; set; }
    }

    // ─────────────────────────────────────────
    // Request DTOs
    // ─────────────────────────────────────────
    public class AddAppointmentPreBookingRequest
    {
        public string? custcode { get; set; }
        public int? dcode { get; set; }
        public string? husband_name { get; set; }
        public string? service_type { get; set; }
        public string? test_name { get; set; }
        public DateTime? appointment_date { get; set; }
        public string? remarks { get; set; }
        public int usercode { get; set; } = 1;
        public int computercode { get; set; } = 1;
    }

    public class UpdateAppointmentPreBookingRequest
    {
        public long preferenceid { get; set; }
        public string? custcode { get; set; }
        public int? dcode { get; set; }
        public string? husband_name { get; set; }
        public string? service_type { get; set; }
        public string? test_name { get; set; }
        public DateTime? appointment_date { get; set; }
        public string? remarks { get; set; }
        public int usercode { get; set; } = 1;
        public int computercode { get; set; } = 1;
    }
    public class MarkVisitedRequest
    {
        public long preferenceid { get; set; }
        public string? in1 { get; set; }
        public string? in2 { get; set; }
        public string? in3 { get; set; }
        public string? in4 { get; set; }
        public string? in5 { get; set; }
        public string? test_name { get; set; }
        public TimeOnly? arrival_time { get; set; }
        public bool is_vip { get; set; } = false;
        public int usercode { get; set; } = 1;
        public int computercode { get; set; } = 1;
    }
}